export namespace globalArrays {
    export const bonkMemeUrls = [
        'https://i.kym-cdn.com/photos/images/newsfeed/001/842/713/b73.jpg',
        'https://i.redd.it/s897cyurzpe51.jpg',
        'https://funvizeo.com/media/memes/8f8236034b498dcd/go-to-horny-jail-moans-sed-bonking-noise-meme-2119d384a4c39ef1-57964a3a96aa649e.jpg',
        'https://lolpics.com/wp-content/uploads/2020/10/Sorry-ladies.jpg',
        'https://img-9gag-fun.9cache.com/photo/apGRLrp_460s.jpg',
        'https://i.redd.it/u1q0erv2gar51.jpg',
        'https://i.imgur.com/ve1UgLs.jpg',
        'https://static.wikia.nocookie.net/562b6bed-8f58-4dca-b693-26e325a7e763',
        'https://i.pinimg.com/564x/cf/36/49/cf3649bf5a8b702fa6123c0235683f8f.jpg',
        'https://pbs.twimg.com/media/EaSlYnOU4AAKnbw.jpg',
        'https://64.media.tumblr.com/82c0ed15f3233f6c036864ded62348ae/11ccb39988acfd91-2e/s1280x1920/41d93f59b500f05cc01df84f3164a2703ebc72fb.jpg',
        'https://lolpics.com/wp-content/uploads/2020/12/Consequences_2.jpg',
        'https://64.media.tumblr.com/1259f0839a07330734ab270dd9eb6656/2682e8d65435e55d-b9/s540x810/f20f224db9501fc6395ef228b39b55025b1ab736.png',
        'https://64.media.tumblr.com/868623aa7ca279d0592f7d0b45a21ddb/d5a5db7b9fc30e6b-b0/s640x960/a28b8bfec7bc0caffe6c72848e5e0626ca9cbf8c.jpg',
        'https://64.media.tumblr.com/07b37de392925fce02bb870ef3babe0e/d5a5db7b9fc30e6b-91/s500x750/3dbf9bb021ec8229d566a9e7f3d2d512291c23d5.jpg',
        'https://i.redd.it/xhbvp2wbj5f61.png',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3zjIfROgR4Q9I0mWsGuxDeMRp59ygKlRNkQ&usqp=CAU',
        'https://i.redd.it/qcpz7rrpt9z51.png',
        'https://pbs.twimg.com/media/EaSlYnIUwAA7Q0v?format=jpg&name=medium',
        'https://i.kym-cdn.com/photos/images/original/002/032/806/d6b.jpg',
        'https://i.kym-cdn.com/photos/images/original/002/032/806/d6b.jpg',
        'https://starecat.com/content/wp-content/uploads/dog-anti-bonk-helmet-doge.jpg',
        'https://img-9gag-fun.9cache.com/photo/aV70r4O_460s.jpg',
        'https://pbs.twimg.com/media/Enc5buwXcAItjnb.png',
        'https://64.media.tumblr.com/82c0ed15f3233f6c036864ded62348ae/11ccb39988acfd91-2e/s1280x1920/41d93f59b500f05cc01df84f3164a2703ebc72fb.jpg',
        'https://ahseeit.com//king-include/uploads/2020/10/needed-bonk-them-and-send-them-horny-jail-sir-assaulted-thousands-horny-people-with-baseball-bat-9130351705.jpg',
        'https://i.kym-cdn.com/photos/images/facebook/002/038/897/2ca.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMkmBhuJF7s2z-luZAMB8rofJlrDkQjH5HnA&usqp=CAU',
        'https://i.redd.it/6ztypom2wy661.jpg',
        'https://preview.redd.it/slth3by7f8y61.jpg?auto=webp&s=094cab37bb0e2847de52d96df10e0c241164857a',
        'https://i.kym-cdn.com/photos/images/original/001/878/184/c46',
        'https://i.redd.it/8tgtwu30fx761.jpg',
    ]

    export const asciiEmojies = [
        '(ﾉ´ з `)ノ',
        '( ´ ▽ ` ).｡ｏ♡',
        '(´,,•ω•,,)♡',
        '(*≧▽≦)',
        'ɾ⚈▿⚈ɹ',
        '( ﾟ∀ ﾟ)',
        '( ・ ̫・)',
        '( •́ .̫ •̀ )',
        '(▰˘v˘▰)',
        '(・ω・)',
        '✾(〜 ☌ω☌)〜✾',
        '(ᗒᗨᗕ)',
        '(・`ω´・)',
        ':3',
        '>:3',
        'xox',
        '>3<',
        'UwU',
        '*gwomps*',
    ]
    export const eivindSpinner = [
        'han knakk den i to.',
        'han ødela den.',
        'han ble frastjålet den.',
        'han mistet den i et veddemål.',
        'han fikk den konfiskert på Elton John konsert.',
        'den ble konfiskert av dørvakten på vei inn på Hexagon.',
        'han mistet den på dansegulvet',
        'han fikk kjeft av Mamma.',
        'den tok fyr og smeltet.',
        'den spant for fort og havnet i middagstallerkenen på nabobordet.',
        'Erna & Co. la all smitteskyld på fidget spinnere og den måtte kastes',
        'han ble den kuleste i nabolaget.',
        'pausen på 71 grader nord var over og han måtte følge med igjen.',
        'han rage quittet.',
        'han ble oppringt om å bli med i sesong 194 av 4 stjerners middag.',
        'han startet re-watch av Hotell Cæsar for tredje gang.',
        'han ga opp og tok en tidlig helg.',
        'han investerte i Gamestop-aksjer og ble søkkrik.',
    ]

    export const bentHoieLines = [
        'Husk å holde avstand',
        'Er det 1 meter mellom dere? *Drar frem målebånd*',
        'Erna ser deg!',
        'Holde dokk avstand nå bler det utepils te sommaren!',
        'Jaja, fina vêre då',
        'Ka du tagge meg for?',
        'Klare for udepils eller?',
        'Gidde du sedda på Sommartid av Guddfaren?',
        'Har kje tid te å svara, ska ud me mordi',
        'Fuck off, eg e ude å fyre',
        '💩',
        'https://media.tenor.com/images/a1505c6e6d37aa2b7c5953741c0177dc/tenor.gif',
        'Du havna nettopp bakerst i vaksinekøen pga den taggen der',
        'Någen så kan oppdatera meg på tennis-fronten her, faen ka?',
        'E på date me mor te Eivind atm, kan kje svara',
        'Kan hooka deg opp me ein AstraZeneca-dose for ein hundrings bro',
        'Har dokkor hørt om Gustav Vigeland?',
        'Hæ, pølse?',
    ]

    export const emojiesList = [
        '🤬',
        '❤️‍🔥',
        '💩',
        '🤡',
        '👌',
        '🙌',
        '🤜',
        '🖕',
        '🙏',
        '🤢',
        '🤠',
        '💀',
        '✌️',
        '🤏',
        '🖖',
        '🖐️',
        '👋',
        '💪',
        '⚰️',
        '🤲',
        '👐',
        '👏',
        '🌭',
        '🤳',
        '🧠',
        '🛌',
        '👀',
        '🩸',
        '😉',
        '🤗',
        '😪',
        '🤥',
        '👵',
        '👨‍🦯',
        '☂️',
        '🤞🏻',
        '👌🏿',
        '👮🏿‍♂️',
        '🌚',
        '🧼',
        '💊',
        '☢️',
        '🤟🏻',
        '🔐',
        '🤛🏻',
    ]

    export const kanIkkjeTekster = (hasEg?: boolean): string[] => {
        const obj = hasEg ? `du` : 'han'
        return [
            `kan ikkje, får kje lov av farsin :(`,
            `kan ikkje, ${obj} skamtrunte på vei te buen`,
            `kan ikkje, fekk husarrest for å leka me fyrstikker`,
            `kan faktisk, ${obj} fekk lo... ånei kødda, mamma seie nei aligavel`,
            `kan ikkje, ${obj} ska spisa pistasj :3`,
            `kan seff, maen e alltid klar for smellen på quellen`,
            `kan kje, mamma e så streng :(`,
            `kan, men ${obj} e kje klar før jæskla seint på quellen`,
            `får lov, men må ver hjemma før klokkå 9 hvis ikkje får ${obj} kje middag imårå`,
        ]
    }
    export const feseTexts = [
        'har fese',
        'har fese xD',
        'har skamfese',
        'har phese',
        'har drede',
        'traff deg i fjese',
        'har blitt fese på',
        'brukte speil, så du traff deg sjøl i fjese der',
        'traff Thomas i fleisen',
        'nuka dassen',
        'slapp ein silent but deadly ein',
        'feis i 32.45 sekund. Helwerre',
        'hadde kebab i går og sidde fortsatt på dassen',
        'feis og brukte med ein feil både speil og skjold på seg sjøl',
        'fise akkurat nå',
        '🪞',
        'trunte rett inn i fisen te Thomas',
        'blei eid av et speil',
    ]
}

export namespace globals {
    export const TIMEOUT_TIME = {
        time: 60000,
        name: '60 sekunder',
    }
}

export interface shopItem {
    name: string
    description: string
    price: string
}
