import { ItemRarity } from '../../../interfaces/database/databaseInterface'
import { CCGCard, CCGCardType } from '../ccgInterface'

export const hpCCG: CCGCard[] = [
    // ── COMMON ─────────────────────────────────────────────────────────────

    {
        id: 'hp_neville_n',
        name: 'Neville Longbottom',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                // 50% chance of giving 1 energy to opponent
                type: 'GAIN_ENERGY',
                target: 'OPPONENT',
                value: 1,
                condition: { type: 'RANDOM', target: 'SELF', chance: 50 },
            },
        ],
        cost: 0,
        speed: 25,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_myrtle_n',
        name: 'Moaning Myrtle',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 4,
            },
        ],
        cost: 1,
        speed: 21,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_umbridge_n',
        name: 'Dolores Umbridge',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                // Shield is a pool that persists across turns until depleted (no turn limit)
                type: 'SHIELD',
                target: 'SELF',
                value: 2,
            },
            {
                // Armor reduces each incoming attack this turn only
                type: 'ARMOR',
                target: 'SELF',
                value: 2,
                turns: 1,
                includeCurrentTurn: true,
            },
        ],
        customDescription: 'Gain [blue]Shield 2[/blue] and [blue]Armor 2[/blue] this turn.',
        cost: 3,
        speed: 70,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['SLYTHERIN'],
    },
    {
        id: 'hp_filch_n',
        name: 'Argus Filch',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                ignoreDefense: true,
            },
        ],
        customDescription: '[gold]Pierce[/gold]: deal [red]2 damage[/red] (ignores [blue]armor[/blue] and [blue]shield[/blue]).',
        cost: 1,
        speed: 28,
        rarity: ItemRarity.Common,
        accuracy: 80,
    },
    {
        id: 'hp_lockhart_n',
        name: 'Gilderoy Lockhart',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                // 40% chance of applying RETARDED to self
                type: 'RETARDED',
                target: 'SELF',
                value: 1,
                turns: 1,
                condition: { type: 'RANDOM', target: 'SELF', chance: 40 },
            },
        ],
        customDescription: 'Deal [red]4 damage[/red]. [red](40%)[/red] become [purple]retarded[/purple] for 1 turn.',
        cost: 1,
        speed: 44,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_barty_crouch_jr_n',
        name: 'Barty Crouch Jr.',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 3,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_polyjuice_potion_n',
            },
        ],
        customDescription: 'Apply [red]Bleed 1[/red] for 3 turns. Summon **Polyjuice Potion** to hand.',
        cost: 1,
        speed: 30,
        rarity: ItemRarity.Common,
        accuracy: 95,
        identifier: ['DEATH_EATER'],
    },
    {
        id: 'hp_pettigrew_n',
        name: 'Peter Pettigrew',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                // Pettigrew is a Death Eater himself, so >=2 means another Death Eater was played alongside him
                type: 'SHIELD',
                target: 'SELF',
                value: 1,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'DEATH_EATER',
                    comparator: '>=',
                    value: 2,
                },
            },
        ],
        customDescription: 'Deal [red]2 damage[/red]. Gain [blue]1 shield[/blue] if played with a [red]Death Eater[/red].',
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Common,
        accuracy: 95,
        identifier: ['GRYFFINDOR', 'DEATH_EATER'],
    },
    {
        id: 'hp_flitwick_n',
        name: 'Filius Flitwick',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // 2 + 1 bonus if played alongside another Ravenclaw (flitwick counts as 1, needs >=2 total)
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        customDescription: 'Gain [blue]2 energy[/blue] + [blue]1 extra[/blue] if played with another [purple]Ravenclaw[/purple].',
        cost: 0,
        speed: 25,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_finnigan_n',
        name: 'Seamus Finnigan',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                // 50% chance of blowing up yourself
                type: 'DAMAGE',
                target: 'SELF',
                value: 2,
                accuracy: 50,
            },
        ],
        customDescription: 'Deal [red]4 damage[/red]. [red](50%)[/red] blow yourself up for [red]2 damage[/red].',
        cost: 1,
        speed: 35,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_fleur_n',
        name: 'Fleur Delacour',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 4,
                gambleGroup: 'fleur',
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                gambleGroup: 'fleur',
            },
        ],
        customDescription: '[red]50%[/red]: [green]Heal 4[/green] or deal [red]3 damage[/red].',
        cost: 1,
        speed: 37,
        rarity: ItemRarity.Common,
        accuracy: 95,
    },
    {
        id: 'hp_kreacher_n',
        name: 'Kreacher',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // 50% chance each turn (statusAccuracy) to gain 1 energy, for 5 turns
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                turns: 5,
                statusAccuracy: 50,
            },
        ],
        customDescription: 'Each turn for 5 turns: [red]50%[/red] chance to gain [blue]1 energy[/blue].',
        cost: 0,
        speed: 10,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['HOUSE_ELF'],
    },

    // ── RARE ───────────────────────────────────────────────────────────────

    {
        id: 'hp_draco_n',
        name: 'Draco Malfoy',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 6,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'DEATH_EATER',
            },
            {
                // Same mechanic as Dark Mark: caster's next card matching `identifier` deals bonus damage
                type: 'DEATH_EATER_BOUNTY',
                target: 'SELF',
                value: 3,
                identifier: 'DEATH_EATER',
            },
        ],
        customDescription: 'Deal [red]6 damage[/red]. Summon a random [purple]Death Eater[/purple]. [gold]Bounty 3: Death Eater[/gold].',
        cost: 3,
        speed: 45,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['SLYTHERIN', 'SEEKER', 'DEATH_EATER'],
    },
    {
        id: 'hp_hagrid_n',
        name: 'Rubeus Hagrid',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // value reduces the summoned creature's cost (baked into the summoned instance, lasts until played)
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'MAGICAL_CREATURE',
                value: 3,
            },
        ],
        customDescription: 'Summon a random [yellow]Magical Creature[/yellow] with [blue]3 less cost[/blue].',
        cost: 1,
        speed: 10,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_slughorn_n',
        name: 'Horace Slughorn',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Collect a random card from the opponent's deck; value = permanent cost reduction
                type: 'COLLECT_CARD',
                target: 'OPPONENT',
                value: 1,
            },
            {
                // Put a random potion on top of your own deck
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'POTION',
                toDeckTop: true,
            },
        ],
        cost: 2,
        speed: 30,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['SLYTHERIN'],
        customDescription:
            "Collect a card from the opponent's deck — its cost is permanently reduced by [blue]1[/blue].\nPut a random [yellow]potion[/yellow] on top of your deck.",
    },
    {
        id: 'hp_shacklebolt_n',
        name: 'Kingsley Shacklebolt',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 5,
            },
            {
                // Auror: if the opponent played a Death Eater this round, permanently raise that card's cost by 1
                type: 'AUROR',
                target: 'OPPONENT',
            },
        ],
        customDescription: 'Deal [red]5 damage[/red]. [grey]Auror[/grey]',
        cost: 2,
        speed: 89,
        rarity: ItemRarity.Rare,
        accuracy: 90,
        identifier: ['AUROR'],
    },
    {
        id: 'hp_nymphadora_n',
        name: 'Nymphadora Tonks',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_lupin_n',
                toDeckTop: true,
            },
        ],
        customDescription: '[green]Heal 3[/green]. Put **Remus Lupin** on top of your deck.',
        cost: 1,
        speed: 100,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['HUFFLEPUFF', 'AUROR'],
    },
    {
        id: 'hp_lucius_n',
        name: 'Lucius Malfoy',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                // 25% "keeps his wand" (flavor) => permanently reduce Lucius's own cost by 1 (no identifier => matches this card)
                type: 'MODIFY_COST_PERMANENT',
                target: 'SELF',
                value: -1,
                condition: { type: 'RANDOM', target: 'SELF', chance: 50 },
            },
        ],
        customDescription: 'Deal [red]4 damage[/red]. [grey](50%)[/grey] keeps his wand — Lucius permanently costs [blue]1 less[/blue].',
        cost: 3,
        speed: 40,
        rarity: ItemRarity.Rare,
        accuracy: 85,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
    },
    {
        id: 'hp_luna_n',
        name: 'Luna Lovegood',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
                condition: { type: 'RANDOM', target: 'SELF', chance: 50 },
            },
        ],
        customDescription: 'Deal [red]2 damage[/red]. [grey](50%)[/grey] heal [green]2[/green].',
        cost: 1,
        speed: 75,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_molly_n',
        name: 'Molly Weasley',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                // Shield is a persistent pool (no turn limit)
                type: 'SHIELD',
                target: 'SELF',
                value: 3,
            },
            {
                // Armor reduces each incoming attack this turn only
                type: 'ARMOR',
                target: 'SELF',
                value: 3,
                turns: 1,
                includeCurrentTurn: true,
            },
        ],
        customDescription: 'Gain [blue]Shield 3[/blue] and [blue]Armor 3[/blue] this turn.',
        cost: 3,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_fred_n',
        name: 'Fred Weasley',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
            },
            {
                // Paired bonus: gain 1 energy + set off a prank (prank lives on Fred only to avoid double-firing)
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_george_n',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'PRANK',
                target: 'SELF',
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_george_n',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        customDescription: '[green]Heal 3[/green]. Paired with George: Gain [blue]1 energy[/blue] and [gold]set off a random prank![/gold]',
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_george_n',
        name: 'George Weasley',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
        ],
        customDescription: 'Deal [red]3 damage[/red]. Paired with Fred: [gold]set off a random prank![/gold]',
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_arthur_n',
        name: 'Arthur Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Shuffle a junk Rubber Duck into the opponent's deck
                type: 'SHUFFLE_CARD',
                target: 'OPPONENT',
                summonCardId: 'hp_rubber_duck_n',
            },
        ],
        customDescription: "Shuffle a [yellow]Rubber Duck[/yellow] into the opponent's deck.",
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_cedric_n',
        name: 'Cedric Diggory',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'FORESIGHT',
                target: 'SELF',
                value: 1,
                charges: 3,
            },
        ],
        customDescription: 'Deal [red]2 damage[/red]. [gold]Foresight 3[/gold].',
        cost: 3,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['HUFFLEPUFF', 'SEEKER'],
    },
    {
        id: 'hp_trelawney_n',
        name: 'Sybill Trelawney',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'VIEW_HAND',
                target: 'SELF',
                turns: 3,
            },
            {
                type: 'SLOW',
                target: 'OPPONENT',
                value: 1,
                turns: 2,
            },
        ],
        customDescription: "See the opponent's hand for the next 3 turns. Apply [purple]Slow[/purple] for 2 turns.",
        cost: 2,
        speed: 5,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_krum_n',
        name: 'Viktor Krum',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 3,
            },
            {
                // 10% chance of catching the Golden Snitch
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_golden_snitch_n',
                condition: { type: 'RANDOM', target: 'SELF', chance: 5 },
            },
        ],
        customDescription: 'Deal [red]3 damage[/red] to [red]both players[/red]. [red](5%)[/red] catch the [gold]Snitch[/gold].',
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['SEEKER'],
    },
    {
        id: 'hp_polyjuice_potion_n',
        name: 'Polyjuice Potion',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'COPY_CARD',
                target: 'OPPONENT',
            },
        ],
        customDescription: "Copy opponent's last played card and add it to your deck.",
        cost: 0,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_felix_felicis_n',
        name: 'Felix Felicis',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'CANNOT_MISS',
                target: 'SELF',
                turns: 3,
                includeCurrentTurn: true,
            },
        ],
        customDescription: 'All your cards are [yellow]100% accurate[/yellow] for 3 turns',
        cost: 0,
        speed: 99,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_amortentia_n',
        name: 'Amortentia',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'NEUTRALIZE_ATTACK',
                target: 'OPPONENT',
            },
        ],
        customDescription: 'Opponent loves you too much to attack you. Neutralize an attack.',
        cost: 1,
        speed: 99,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_draught_of_living_death_n',
        name: 'Draught of Living Death',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'SLEEP',
                target: 'OPPONENT',
                turns: 1,
            },
        ],
        customDescription: 'Opponent [purple]SLEEPS[/purple] for 1 turn',
        cost: 2,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },

    // ── EPIC ───────────────────────────────────────────────────────────────

    {
        id: 'hp_ginny_n',
        name: 'Ginny Weasley',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'NEUTRALIZE_ATTACK',
                target: 'OPPONENT',
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 4,
            },
        ],
        customDescription: '[gold]Shut it![/gold] Negate an incoming attack and [green]heal 4[/green].',
        cost: 2,
        speed: 95, // high so the negate resolves before incoming attacks land
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_aragog_n',
        name: 'Aragog',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 20,
            },
        ],
        customDescription: 'Apply [red]Bleed 1[/red] to the opponent for [red]20 turns[/red].',
        cost: 2,
        speed: 53,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_buckbeak_n',
        name: 'Buckbeak',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                // Persistent shield pool
                type: 'SHIELD',
                target: 'SELF',
                value: 1,
            },
            {
                // Armor reduces each incoming attack this turn
                type: 'ARMOR',
                target: 'SELF',
                value: 1,
                turns: 1,
                includeCurrentTurn: true,
            },
            {
                // One-time saving grace: negates a single lethal hit this turn and heals 1 (value). Consumed on use.
                type: 'CANNOT_DIE',
                target: 'SELF',
                value: 3,
                turns: 1,
                includeCurrentTurn: true,
            },
        ],
        customDescription:
            'Gain [blue]Shield 1[/blue] and [blue]Armor 1[/blue]. If a lethal hit would kill you this turn, negate it and [green]heal 3[/green] instead.',
        cost: 2,
        speed: 95,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    ((): CCGCard => {
        const retardedTurns = 1
        return {
            id: 'hp_hermione_n',
            name: 'Hermione Granger',
            series: 'hpCCG',
            type: CCGCardType.Heal,
            effects: [
                {
                    type: 'RETARDED',
                    target: 'OPPONENT',
                    value: 1,
                    turns: retardedTurns,
                },
                {
                    type: 'HEAL',
                    target: 'SELF',
                    value: 4,
                },
            ],
            customDescription: `[gold]Confund[/gold] the opponent — they are [purple]Retarded[/purple] for ${retardedTurns} turn${
                retardedTurns !== 1 ? 's' : ''
            }. [green]Heal 4[/green].`,
            cost: 3,
            speed: 70,
            rarity: ItemRarity.Legendary,
            accuracy: 100,
            identifier: ['GRYFFINDOR'],
        }
    })(),
    {
        id: 'hp_ron_n',
        name: 'Ron Weasley',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                // Move Fred & George to the top of the draw pile if they're still in the deck
                type: 'MOVE_TO_TOP',
                target: 'SELF',
                cardIds: ['hp_fred_n', 'hp_george_n'],
            },
        ],
        customDescription: 'Deal [red]4 damage[/red]. Move [gold]Fred[/gold] & [gold]George[/gold] to the top of your draw pile.',
        cost: 2,
        speed: 20,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_sirius_n',
        name: 'Sirius Black',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE_BY_RESOLVE_ORDER',
                target: 'OPPONENT',
            },
        ],
        customDescription: "Deal damage equal to this card's resolve order (1st = 1, 4th = 4).",
        cost: 2,
        speed: 68,
        rarity: ItemRarity.Epic,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_mcgonagall_n',
        name: 'Minerva McGonagall',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                type: 'REFLECT',
                target: 'SELF',
                value: 1,
                turns: 1,
                includeCurrentTurn: true,
                reflectType: 'allEffects',
            },
        ],
        customDescription: 'Reflect all effects targeting you this turn.',
        cost: 2,
        speed: 100,
        rarity: ItemRarity.Epic,
        accuracy: 99,
        cannotMiss: true,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_dobby_n',
        name: 'Dobby',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'RECOVER',
                target: 'SELF',
                value: 1,
                turns: 2,
            },
        ],
        cost: 0,
        speed: 80,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['HOUSE_ELF'],
    },
    {
        id: 'hp_bellatrix_n',
        name: 'Bellatrix Lestrange',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // +1 to your damage for 2 turns
                type: 'DAMAGE_BOOST',
                target: 'SELF',
                value: 1,
                turns: 2,
            },
            {
                // Reduce the opponent's heals by 1 for 2 turns
                type: 'HEAL_REDUCTION',
                target: 'OPPONENT',
                value: 1,
                turns: 2,
            },
        ],
        customDescription: 'Increase your [red]damage by 1[/red] for 2 turns. Reduce the opponent’s [green]heals by 1[/green] for 2 turns.',
        cost: 0,
        speed: 15,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
    },
    {
        id: 'hp_madeye_n',
        name: 'Mad-Eye Moody',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // EXTRA_CARDS value is the absolute max cards allowed; default maxCardsPlayed is 2, so 3 = one extra
                type: 'EXTRA_CARDS',
                target: 'SELF',
                value: 3,
                turns: 2,
            },
            {
                // Auror: if the opponent played a Death Eater this round, permanently raise that card's cost by 1
                type: 'AUROR',
                target: 'OPPONENT',
            },
        ],
        customDescription: 'Play [gold]1 extra card[/gold] for 2 turns. [grey]Auror[/grey]',
        cost: 2,
        speed: 10,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['AUROR'],
    },
    {
        id: 'hp_lupin_n',
        name: 'Remus Lupin',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Persistent shield pool
                type: 'SHIELD',
                target: 'SELF',
                value: 3,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_nymphadora_n',
                toDeckTop: true,
            },
            {
                type: 'TRANSFORM',
                target: 'SELF',
                accuracy: 50,
                transformCardId: 'hp_werewolf_n',
            },
        ],
        cost: 2,
        speed: 70,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['GRYFFINDOR'],
        customDescription: 'Gain [blue]3 shield[/blue]. Put **Tonks** on top of your deck. 50% chance to turn into a [yellow]werewolf[/yellow].',
    },
    {
        id: 'hp_werewolf_n',
        name: 'Werewolf',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
        ],
        cost: 2,
        speed: 45,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
        collectible: false,
    },
    {
        id: 'hp_fawkes_n',
        name: 'Fawkes',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                // value acts as a multiplier on the opponent's total spent cost
                type: 'HEAL_PER_OPPONENT_COST',
                target: 'SELF',
                value: 2,
            },
        ],
        customDescription: "[green]Heal[/green] equal to [green]2x[/green] the total cost of opponent's cards played this round.",
        cost: 2,
        speed: 70,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_basilisk_n',
        name: 'Basilisk',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE_PER_OPPONENT_COST',
                target: 'OPPONENT',
            },
        ],
        customDescription: "[red]Deal damage[/red] equal to the total cost of opponent's cards played this round.",
        cost: 2,
        speed: 55,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_dark_mark_n',
        name: 'Dark Mark',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Summon two random Death Eater cards to hand
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'DEATH_EATER',
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'DEATH_EATER',
            },
            {
                // Bounty 3: the next card matching `identifier` you play deals 3 bonus damage (consumed on trigger)
                type: 'DEATH_EATER_BOUNTY',
                target: 'SELF',
                value: 3,
                identifier: 'DEATH_EATER',
            },
        ],
        customDescription: 'Summon [red]2 random Death Eaters[/red]. [gold]Bounty 3: Death Eater[/gold].',
        cost: 1,
        speed: 20,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },

    // ── LEGENDARY ─────────────────────────────────────────────────────────

    ((): CCGCard => {
        const reduceCostTurns = 1
        const snitchChance = 5
        return {
            id: 'hp_harry_potter_n',
            name: 'Harry Potter',
            series: 'hpCCG',
            type: CCGCardType.Attack,
            effects: [
                {
                    // Expeliarmus: opponent's cards cost 2 more for reduceCostTurns turn(s)
                    type: 'REDUCE_COST',
                    target: 'OPPONENT',
                    value: -2,
                    turns: reduceCostTurns,
                },
                {
                    type: 'DAMAGE',
                    target: 'OPPONENT',
                    value: 3,
                },
                {
                    type: 'SUMMON_CARD',
                    target: 'SELF',
                    summonCardId: 'hp_golden_snitch_n',
                    condition: { type: 'RANDOM', target: 'SELF', chance: snitchChance },
                },
            ],
            customDescription: `[gold]Expeliarmus![/gold] Opponent's cards cost [red]2 more[/red] for ${reduceCostTurns} turn${
                reduceCostTurns !== 1 ? 's' : ''
            }. Deal [red]3 damage[/red]. [red](${snitchChance}%)[/red] catch the [gold]Snitch[/gold].`,
            cost: 3,
            speed: 72,
            rarity: ItemRarity.Legendary,
            accuracy: 100,
            identifier: ['GRYFFINDOR', 'SEEKER'],
        }
    })(),
    {
        id: 'hp_dumbledore_n',
        name: 'Albus Dumbledore',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                // Permanently discard a random card from your own deck
                type: 'SACRIFICE_CARD',
                target: 'SELF',
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 6,
            },
            {
                // 5% chance to take 30 damage to yourself (effectively death)
                type: 'DAMAGE',
                target: 'SELF',
                value: 30,
                condition: { type: 'RANDOM', target: 'SELF', chance: 5 },
            },
        ],
        customDescription: 'Sacrifice a random card from your deck to deal [red]6 damage[/red]. [red](5%)[/red] you die instantly.',
        cost: 1,
        speed: 10,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_snape_n',
        name: 'Severus Snape',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                type: 'SHIELD',
                target: 'SELF',
                value: 6,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'POTION',
            },
        ],
        cost: 3,
        speed: 95,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
        customDescription: 'Gain [blue]Shield 6[/blue]. Make a random [yellow]potion[/yellow].',
    },
    {
        id: 'hp_voldemort_n',
        name: 'Lord Voldemort',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 6,
            },
            {
                type: 'ELUSIVE',
                target: 'SELF',
                turns: 2,
            },
        ],
        customDescription: 'Deal [red]6 damage[/red]. Become [purple]Elusive[/purple] for 2 turns.',
        cost: 3,
        speed: 45,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
    },
    {
        id: 'hp_bertie_botts_n',
        name: "Bertie Bott's Every Flavour Beans",
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'TRANSFORM',
                target: 'SELF',
                transformSeries: 'hpCCG',
            },
        ],
        customDescription: 'Becomes a random [yellow]HP card[/yellow] and resolves it immediately.',
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        nameFontSize: 22,
        collectible: false,
    },
    {
        id: 'hp_expecto_patronum_n',
        name: 'Expecto Patronum',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // value = max-HP increase; amount = how much is actually healed
                type: 'INCREASE_MAX_HP',
                target: 'SELF',
                value: 5,
                amount: 5,
            },
            {
                // Permanently raise the cost of every Death Eater card the opponent owns (hand/deck/used) by 1
                type: 'MODIFY_COST_PERMANENT',
                target: 'OPPONENT',
                value: 1,
                identifier: 'DEATH_EATER',
            },
        ],
        customDescription:
            "Increase max HP by 5 and [green]heal 5[/green]. Permanently raise the cost of all the opponent's [red]Death Eater[/red] cards by [blue]1[/blue]. [grey]Removed from deck once played.[/grey]",
        cost: 4,
        speed: 10,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        consumable: true,
    },

    // ── UNOBTAINABLE ──────────────────────────────────────────────────────
    {
        id: 'hp_golden_snitch_n',
        name: 'Golden Snitch',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                // Catching the snitch = effectively winning. Starting HP is ~20 so 25 damage is lethal.
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 25,
            },
        ],
        customDescription: '⚡ Catch the Snitch! Deal [red]25 damage[/red].',
        cost: 12,
        speed: 70,
        rarity: ItemRarity.Unobtainable,
        accuracy: 99,
        collectible: false,
    },

    // ── JUNK (non-collectible, shuffled into a deck by Arthur) ─────────────────
    {
        id: 'hp_rubber_duck_n',
        name: 'Rubber Duck',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 1,
            },
        ],
        customDescription: 'Deal [red]1 damage[/red]. [grey]Permanently removed if discarded.[/grey]',
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
        removeOnDiscard: true,
    },

    // ── PRANKS (non-collectible, triggered by Fred+George) ─────────────────────

    {
        id: 'hp_prank_damage_n',
        name: 'Prank: Dungbomb',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [{ type: 'DAMAGE', target: 'OPPONENT', value: 3 }],
        customDescription: 'Deal [red]3 damage[/red] to the opponent.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_shield_n',
        name: 'Prank: Decoy Detonator',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [{ type: 'SHIELD', target: 'SELF', value: 2 }],
        customDescription: 'Gain [blue]Shield 2[/blue].',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_both_n',
        name: 'Prank: Wildfire Whiz-bang',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            { type: 'DAMAGE', target: 'OPPONENT', value: 3 },
            { type: 'DAMAGE', target: 'SELF', value: 3 },
        ],
        customDescription: 'Deal [red]3 damage[/red] to both players.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_energy_n',
        name: 'Prank: Ton-Tongue Toffee',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'SWAP_ENERGY', target: 'OPPONENT' }],
        customDescription: 'Both players swap [blue]energy[/blue].',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_darkness_powder_n',
        name: 'Prank: Peruvian Instant Darkness Powder',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'BLANK_HAND', target: 'OPPONENT', turns: 1, includeCurrentTurn: false }],
        customDescription: "The opponent's cards are [grey]blank[/grey] next turn — only cost is visible.",
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_hiccough_sweets_n',
        name: 'Prank: Hiccough Sweets',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            { type: 'RANDOMIZE_COST', target: 'SELF', value: 0, turns: 3 },
            { type: 'RANDOMIZE_COST', target: 'OPPONENT', value: 0, turns: 3 },
        ],
        customDescription: 'All card costs are [gold]randomized (0–5)[/gold] for 3 turns.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_fainting_fancy_n',
        name: 'Prank: Fainting Fancy',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'EQUALIZE_HP', target: 'OPPONENT' }],
        customDescription: "Both players' HP is set to the [green]average[/green] (rounded down).",
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_fever_fudge_n',
        name: 'Prank: Fever Fudge',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            { type: 'RANDOMIZE_ACCURACY', target: 'SELF', turns: 2, includeCurrentTurn: false },
            { type: 'RANDOMIZE_ACCURACY', target: 'OPPONENT', turns: 2, includeCurrentTurn: false },
        ],
        customDescription: 'All cards have [gold]randomized accuracy[/gold] (1–99) for 2 turns.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_sorting_jinx_n',
        name: 'Prank: Sorting Jinx',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'SORT_DECK', target: 'OPPONENT' }],
        customDescription:
            "Sort the opponent's deck unfavorably by cost — [red]cheapest first[/red] if they have [blue]>4 energy[/blue], [red]priciest first[/red] otherwise.",
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_confundus_n',
        name: 'Prank: Confundus Candy',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'OBFUSCATE_HAND', target: 'OPPONENT', turns: 1, includeCurrentTurn: false }],
        customDescription: 'Opponent\'s card buttons are [grey]shuffled[/grey] and show only "Card" next turn.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_malfunction_n',
        name: 'Prank: Malfunction',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [{ type: 'DAMAGE', target: 'SELF', value: 7 }],
        customDescription: 'Take [red]7 damage[/red].',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_rubber_duck_fill_n',
        name: 'Prank: Rubber Duck',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [{ type: 'FILL_HAND_RUBBER_DUCK', target: 'OPPONENT' }],
        customDescription: 'Both players discard their hand and draw [gold]Rubber Ducks[/gold].',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
]
