import { ItemRarity } from '../../../interfaces/database/databaseInterface'
import { CCGCard, CCGCardType } from '../ccgInterface'

export const hpCCG: CCGCard[] = [
    // ── COMMON ─────────────────────────────────────────────────────────────

    {
        id: 'hp_neville_n',
        name: 'Neville Longbottom',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                // 50% chance of giving 1 energy to opponent
                type: 'GAIN_ENERGY',
                target: 'OPPONENT',
                value: 1,
                condition: { type: 'RANDOM', target: 'SELF', chance: 50 },
            },
        ],
        cost: 0,
        speed: 25,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_myrtle_n',
        name: 'Moaning Myrtle',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 3,
            },
        ],
        cost: 1,
        speed: 21,
        rarity: ItemRarity.Common,
        accuracy: 85,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_umbridge_n',
        name: 'Dolores Umbridge',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                // identifier on ARMOR means it only reduces damage from cards with that identifier
                type: 'ARMOR',
                target: 'SELF',
                value: 1,
                turns: 2,
                identifier: 'GRYFFINDOR',
            },
        ],
        customDescription: 'Reduce damage from [gold]Gryffindor[/gold] cards by 1 for **2 turns**.',
        cost: 1,
        speed: 100,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['SLYTHERIN'],
    },
    {
        id: 'hp_filch_n',
        name: 'Argus Filch',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        cost: 1,
        speed: 28,
        rarity: ItemRarity.Common,
        accuracy: 80,
    },
    {
        id: 'hp_lockhart_n',
        name: 'Gilderoy Lockhart',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                // 30% chance of applying RETARDED to self
                type: 'RETARDED',
                target: 'SELF',
                value: 1,
                turns: 1,
                condition: { type: 'RANDOM', target: 'SELF', chance: 30 },
            },
        ],
        cost: 1,
        speed: 44,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_ginny_n',
        name: 'Ginny Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'REMOVE_STATUS',
                target: 'SELF',
                value: 99,
            },
        ],
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_barty_crouch_jr_n',
        name: 'Barty Crouch Jr.',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 2,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_polyjuice_potion_n',
            },
        ],
        customDescription: 'Apply [red]Bleed 1[/red] for 2 turns. Summon **Polyjuice Potion** to hand.',
        cost: 1,
        speed: 30,
        rarity: ItemRarity.Common,
        accuracy: 95,
        identifier: ['DEATH_EATER'],
    },
    {
        id: 'hp_pettigrew_n',
        name: 'Peter Pettigrew',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_voldemort_n',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_voldemort_n',
                    comparator: '>=',
                    value: 1,
                    invert: true,
                },
            },
        ],
        customDescription: 'Deal [red]3 damage[/red] if Voldemort was played this round, otherwise [red]2 damage[/red].',
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Common,
        accuracy: 80,
        identifier: ['GRYFFINDOR', 'DEATH_EATER'],
    },
    {
        id: 'hp_flitwick_n',
        name: 'Filius Flitwick',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // 1 + 2 bonus if played alongside another Ravenclaw (flitwick counts as 1, needs >=2 total)
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        customDescription: 'Gain [blue]1 energy[/blue] + [blue]2 extra[/blue] if played with another [purple]Ravenclaw[/purple].',
        cost: 0,
        speed: 25,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_finnigan_n',
        name: 'Seamus Finnigan',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                // 25% chance of blowing up yourself
                type: 'DAMAGE',
                target: 'SELF',
                value: 2,
                accuracy: 25,
            },
        ],
        customDescription: 'Deal [red]2 damage[/red]. [red](25%)[/red] blow yourself up for [red]3 damage[/red].',
        cost: 1,
        speed: 35,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_fleur_n',
        name: 'Fleur Delacour',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 1,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
            },
        ],
        cost: 1,
        speed: 37,
        rarity: ItemRarity.Common,
        accuracy: 85,
    },
    {
        id: 'hp_kreacher_n',
        name: 'Kreacher',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
        ],
        cost: 0,
        speed: 10,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['HOUSE_ELF'],
    },
    {
        id: 'hp_aragog_n',
        name: 'Aragog',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 1,
            },
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 2,
            },
        ],
        cost: 1,
        speed: 53,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },

    // ── RARE ───────────────────────────────────────────────────────────────

    {
        id: 'hp_draco_n',
        name: 'Draco Malfoy',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                // 1% chance of catching the Golden Snitch (adds it to hand)
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_golden_snitch_n',
                condition: { type: 'RANDOM', target: 'SELF', chance: 1 },
            },
        ],
        cost: 1,
        speed: 45,
        rarity: ItemRarity.Rare,
        accuracy: 85,
        identifier: ['SLYTHERIN', 'SEEKER', 'DEATH_EATER'],
    },
    {
        id: 'hp_hagrid_n',
        name: 'Rubeus Hagrid',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'REDUCE_COST',
                target: 'SELF',
                value: 1,
                turns: 2,
                identifier: 'MAGICAL_CREATURE',
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'MAGICAL_CREATURE',
            },
        ],
        cost: 1,
        speed: 10,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_slughorn_n',
        name: 'Horace Slughorn',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'STEAL_ENERGY',
                target: 'OPPONENT',
                value: 1,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'POTION',
            },
        ],
        cost: 2,
        speed: 30,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['SLYTHERIN'],
        customDescription: 'Steal [blue]1 energy[/blue] from opponent.\nMake a random [yellow]potion[/yellow]',
    },
    {
        id: 'hp_shacklebolt_n',
        name: 'Kingsley Shacklebolt',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
            },
        ],
        cost: 1,
        speed: 62,
        rarity: ItemRarity.Rare,
        accuracy: 90,
    },
    {
        id: 'hp_nymphadora_n',
        name: 'Nymphadora Tonks',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                // Removes all negative status conditions from self (primarily intended to neutralize Bleed)
                type: 'REMOVE_STATUS',
                target: 'SELF',
                value: 99,
            },
        ],
        customDescription: 'Remove all [red]Bleed[/red] and status conditions from self.',
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['HUFFLEPUFF'],
    },
    {
        id: 'hp_lucius_n',
        name: 'Lucius Malfoy',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                // +1 bonus damage if opponent played a House Elf card this round
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'HOUSE_ELF',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'HOUSE_ELF',
                    comparator: '>=',
                    value: 1,
                    invert: true,
                },
            },
        ],
        customDescription: 'Deal [red]3 damage[/red] if opponent played a [grey]House Elf[/grey], otherwise [red]2 damage[/red].',
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Rare,
        accuracy: 85,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
    },
    {
        id: 'hp_luna_n',
        name: 'Luna Lovegood',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                // +2 bonus if played alongside another Ravenclaw (luna counts as 1, needs >=2 total)
                type: 'HEAL',
                target: 'SELF',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 1,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'RAVENCLAW',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        customDescription: 'Heal [green]1[/green] + [green]2 extra[/green] if played with another [purple]Ravenclaw[/purple].',
        cost: 0,
        speed: 65,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_molly_n',
        name: 'Molly Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                // Deal 2 damage if opponent played a Death Eater this round
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'DEATH_EATER',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        customDescription: 'Gain [blue]2 energy[/blue]. Deal [red]2 damage[/red] if opponent played a [red]Death Eater[/red].',
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_fred_n',
        name: 'Fred Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'PRANK',
                target: 'SELF',
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_george_n',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        customDescription: 'Gain [blue]2 energy[/blue]. Paired with George: [gold]Set off a random prank![/gold]',
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 85,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_george_n',
        name: 'George Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'PRANK',
                target: 'SELF',
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'hp_fred_n',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        customDescription: 'Gain [blue]2 energy[/blue]. Paired with Fred: [gold]Set off a random prank![/gold]',
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 85,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_arthur_n',
        name: 'Arthur Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Negative value on REDUCE_COST = cost increase. Math: card.cost - (-1) = card.cost + 1.
                type: 'REDUCE_COST',
                target: 'OPPONENT',
                value: -1,
                turns: 1,
            },
        ],
        customDescription: "Increase cost of all opponent's cards by 1 for 1 turn.",
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_cedric_n',
        name: 'Cedric Diggory',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                // 1% chance of catching the Golden Snitch
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_golden_snitch_n',
                condition: { type: 'RANDOM', target: 'SELF', chance: 1 },
            },
        ],
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 99,
        identifier: ['HUFFLEPUFF', 'SEEKER'],
    },
    {
        id: 'hp_trelawney_n',
        name: 'Sybill Trelawney',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'SLOW',
                target: 'OPPONENT',
                value: 1,
                turns: 3,
            },
        ],
        cost: 2,
        speed: 5,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['RAVENCLAW'],
    },
    {
        id: 'hp_krum_n',
        name: 'Viktor Krum',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                // 1% chance of catching the Golden Snitch
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_golden_snitch_n',
                condition: { type: 'RANDOM', target: 'SELF', chance: 1 },
            },
        ],
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['SEEKER'],
    },
    {
        id: 'hp_buckbeak_n',
        name: 'Buckbeak',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'HEAL_BOOST',
                target: 'SELF',
                value: 1,
                turns: 2,
            },
        ],
        customDescription: 'Increase all heals by 1 for **2 turns**.',
        cost: 1,
        speed: 20,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_polyjuice_potion_n',
        name: 'Polyjuice Potion',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'COPY_CARD',
                target: 'OPPONENT',
            },
        ],
        customDescription: "Copy opponent's last played card and add it to your deck.",
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_felix_felicis_n',
        name: 'Felix Felicis',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'CANNOT_MISS',
                target: 'SELF',
                turns: 3,
                includeCurrentTurn: true,
            },
        ],
        customDescription: 'All your cards are [yellow]100% accurate[/yellow] for 3 turns',
        cost: 0,
        speed: 99,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_amortentia_n',
        name: 'Amortentia',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'NEUTRALIZE_ATTACK',
                target: 'OPPONENT',
            },
        ],
        customDescription: 'Opponent loves you too much to attack you. Neutralize an attack.',
        cost: 1,
        speed: 99,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },
    {
        id: 'hp_draught_of_living_death_n',
        name: 'Draught of Living Death',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'SLEEP',
                target: 'OPPONENT',
                turns: 1,
            },
        ],
        customDescription: 'Opponent [purple]SLEEPS[/purple] for 1 turn',
        cost: 2,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        collectible: false,
        identifier: ['POTION'],
    },

    // ── EPIC ───────────────────────────────────────────────────────────────

    {
        id: 'hp_hermione_n',
        name: 'Hermione Granger',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 4,
            },
            {
                type: 'RECOVER',
                target: 'SELF',
                value: 1,
                turns: 3,
            },
        ],
        cost: 3,
        speed: 70,
        rarity: ItemRarity.Epic,
        accuracy: 99,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_ron_n',
        name: 'Ron Weasley',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                turns: 4,
            },
            {
                type: 'BLEED',
                target: 'SELF',
                value: 1,
                turns: 3,
            },
        ],
        cost: 1,
        speed: 20,
        rarity: ItemRarity.Epic,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_sirius_n',
        name: 'Sirius Black',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'MYGLING',
                target: 'OPPONENT',
                value: 1,
                turns: 1,
            },
        ],
        cost: 2,
        speed: 50,
        rarity: ItemRarity.Epic,
        accuracy: 90,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_mcgonagall_n',
        name: 'Minerva McGonagall',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                type: 'REFLECT',
                target: 'SELF',
                value: 1,
                turns: 1,
                reflectType: 'allEffects',
            },
        ],
        customDescription: 'Reflect all effects targeting you for 1 turn.',
        cost: 1,
        speed: 100,
        rarity: ItemRarity.Epic,
        accuracy: 99,
        cannotMiss: true,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_dobby_n',
        name: 'Dobby',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'RECOVER',
                target: 'SELF',
                value: 1,
                turns: 3,
            },
        ],
        cost: 0,
        speed: 80,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['HOUSE_ELF'],
    },
    {
        id: 'hp_bellatrix_n',
        name: 'Bellatrix Lestrange',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'RESTRICT_CARDS',
                target: 'OPPONENT',
                value: 1,
                turns: 1,
            },
        ],
        customDescription: 'Opponent can only play [red]1 card[/red] next turn.',
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['SLYTHERIN', 'DEATH_EATER'],
    },
    {
        id: 'hp_madeye_n',
        name: 'Mad-Eye Moody',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // EXTRA_CARDS value is the absolute max cards allowed; default maxCardsPlayed is 2, so 3 = one extra
                type: 'EXTRA_CARDS',
                target: 'SELF',
                value: 3,
                turns: 2,
            },
        ],
        cost: 2,
        speed: 10,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },
    {
        id: 'hp_lupin_n',
        name: 'Remus Lupin',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'ARMOR',
                target: 'SELF',
                value: 2,
                turns: 1,
                includeCurrentTurn: true,
            },
            {
                type: 'TRANSFORM',
                target: 'SELF',
                accuracy: 50,
                transformCardId: 'hp_werewolf_n',
            },
        ],
        cost: 2,
        speed: 70,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['GRYFFINDOR'],
        customDescription: 'Gain [blue]2 armor[/blue] this turn. 50% chance to turn into a [yellow]werewolf[/yellow].',
    },
    {
        id: 'hp_werewolf_n',
        name: 'Werewolf',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
        ],
        cost: 2,
        speed: 45,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['MAGICAL_CREATURE'],
        collectible: false,
    },
    {
        id: 'hp_fawkes_n',
        name: 'Fawkes',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL_PER_OPPONENT_COST',
                target: 'SELF',
            },
        ],
        customDescription: "[green]Heal[/green] equal to total cost of opponent's cards played this round.",
        cost: 2,
        speed: 70,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_basilisk_n',
        name: 'Basilisk',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE_PER_OPPONENT_COST',
                target: 'OPPONENT',
            },
        ],
        customDescription: "[red]Deal damage[/red] equal to total cost of opponent's cards played this round.",
        cost: 2,
        speed: 55,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['MAGICAL_CREATURE'],
    },
    {
        id: 'hp_dark_mark_n',
        name: 'Dark Mark',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // Summon a random Death Eater card to hand
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'DEATH_EATER',
            },
            {
                // Delayed trigger: gives 2 energy once after 2 turns, not 2 energy per turn
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
                turns: 2,
                delayedTrigger: true,
            },
        ],
        cost: 1,
        speed: 20,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },

    // ── LEGENDARY ─────────────────────────────────────────────────────────

    {
        id: 'hp_harry_potter_n',
        name: 'Harry Potter',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                // 3% chance of catching the Golden Snitch — adds it to hand
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'hp_golden_snitch_n',
                condition: { type: 'RANDOM', target: 'SELF', chance: 3 },
            },
        ],
        cost: 2,
        speed: 45,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        identifier: ['GRYFFINDOR', 'SEEKER'],
    },
    {
        id: 'hp_dumbledore_n',
        name: 'Albus Dumbledore',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                // value: 99 ensures all Gryffindor cards are effectively free (clamped to 0 cost)
                type: 'REDUCE_COST',
                target: 'SELF',
                value: 99,
                turns: 3,
                identifier: 'GRYFFINDOR',
            },
        ],
        customDescription: '[gold]Gryffindor[/gold] cards cost [blue]0 energy[/blue] for 3 turns.',
        cost: 2,
        speed: 10,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['GRYFFINDOR'],
    },
    {
        id: 'hp_snape_n',
        name: 'Severus Snape',
        series: 'hpCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'POTION',
            },
        ],
        cost: 3,
        speed: 65,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['SLYTHERIN'],
        customDescription: '[green]Heal 2[/green], Deal [red]2 damage[/red] and make a random [yellow]potion[/yellow]',
    },
    {
        id: 'hp_voldemort_n',
        name: 'Lord Voldemort',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
            },
            {
                type: 'REDUCE_COST',
                target: 'SELF',
                value: 1,
                turns: 2,
                identifier: 'DEATH_EATER',
            },
        ],
        cost: 3,
        speed: 45,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        identifier: ['SLYTHERIN'],
    },
    {
        id: 'hp_bertie_botts_n',
        name: "Bertie Bott's Every Flavour Beans",
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'TRANSFORM',
                target: 'SELF',
                transformSeries: 'hpCCG',
            },
        ],
        customDescription: 'Becomes a random [yellow]HP card[/yellow] and resolves it immediately.',
        cost: 2,
        speed: 50,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },
    {
        id: 'hp_expecto_patronum_n',
        name: 'Expecto Patronum',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'INCREASE_MAX_HP',
                target: 'SELF',
                value: 5,
            },
        ],
        customDescription: 'Increase max HP by 5. [grey]Removed from deck once played.[/grey]',
        cost: 5,
        speed: 10,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        consumable: true,
    },

    // ── UNOBTAINABLE ──────────────────────────────────────────────────────
    {
        id: 'hp_golden_snitch_n',
        name: 'Golden Snitch',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                // Catching the snitch = effectively winning. Starting HP is ~20 so 25 damage is lethal.
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 25,
            },
        ],
        customDescription: '⚡ Catch the Snitch! Deal [red]25 damage[/red].',
        cost: 10,
        speed: 80,
        rarity: ItemRarity.Unobtainable,
        accuracy: 99,
        summoned: true,
        collectible: false,
    },

    // ── PRANKS (non-collectible, triggered by Fred+George) ─────────────────────

    {
        id: 'hp_prank_damage_n',
        name: 'Prank: Dungbomb',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        customDescription: 'Deal [red]2 damage[/red] to the opponent.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_shield_n',
        name: 'Prank: Decoy Detonator',
        series: 'hpCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                type: 'ARMOR',
                target: 'SELF',
                value: 1,
                turns: 1,
            },
        ],
        customDescription: 'Reduce the next incoming attack by 1.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_both_n',
        name: 'Prank: Wildfire Whiz-bang',
        series: 'hpCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 2,
            },
        ],
        customDescription: 'Deal [red]2 damage[/red] to both players.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
    {
        id: 'hp_prank_energy_n',
        name: 'Prank: Ton-Tongue Toffee',
        series: 'hpCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
                turns: 2,
            },
        ],
        customDescription: 'Gain [blue]2 energy[/blue] over 2 turns.',
        cost: 0,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 100,
        cannotMiss: true,
        collectible: false,
    },
]
