import { ItemRarity } from '../../../interfaces/database/databaseInterface'
import { CCGCard, CCGCardType } from '../ccgInterface'

export const mazariniCCG: CCGCard[] = [
    {
        id: 'shrekStare',
        name: 'Shrek Stare',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
            },
        ],
        cost: 1,
        speed: 16,
        rarity: ItemRarity.Common,
        accuracy: 99,
    },
    {
        id: 'geggiexcited',
        name: 'Geggi Excited',
        series: 'mazariniCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
            },
        ],
        cost: 1,
        speed: 60,
        rarity: ItemRarity.Common,
        accuracy: 99,
    },
    {
        id: 'arne',
        name: 'Arne',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 1,
            },
        ],
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Common,
        accuracy: 80,
    },
    {
        id: 'arne_caveman',
        name: 'Arne Caveman',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        cost: 1,
        speed: 39,
        rarity: ItemRarity.Common,
        accuracy: 90,
    },
    {
        id: 'pointerbrothers1',
        name: 'PointerBrother 1',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                turns: 5,
            },
        ],
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Epic,
        accuracy: 90,
    },
    {
        id: 'same',
        name: 'Same',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [],
        cost: 2,
        speed: 1,
        rarity: ItemRarity.Epic,
        accuracy: 90,
    },
    {
        id: 'KEKW_gun',
        name: 'KEKW Gun',
        series: 'mazariniCCG',
        type: CCGCardType.Shield,
        effects: [
            {
                type: 'REFLECT',
                target: 'SELF',
                turns: 1,
            },
        ],
        cost: 2,
        speed: 100,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },
    {
        id: 'kms_gun',
        name: 'Kms Gun',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 1,
                turns: 3,
            },
        ],
        cost: 3,
        speed: 45,
        rarity: ItemRarity.Epic,
        accuracy: 90,
    },
    {
        id: 'arnenymous',
        name: 'Arnenymous',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'REDUCE_COST',
                target: 'SELF',
                value: 1,
                turns: 6,
            },
        ],
        cost: 4,
        speed: 6,
        rarity: ItemRarity.Epic,
        accuracy: 90,
    },
    {
        id: 'polse',
        name: 'Pølse',
        series: 'mazariniCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'REMOVE_STATUS',
                target: 'SELF',
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
            },
        ],
        cost: 2,
        speed: 7,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        cannotMiss: true,
    },
    {
        id: 'kys',
        name: 'Kys',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 6,
            },
        ],
        cost: 3,
        speed: 49,
        rarity: ItemRarity.Legendary,
        accuracy: 95,
    },
    {
        id: 'hoie',
        name: 'Høie',
        series: 'mazariniCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 6,
            },
            {
                type: 'REMOVE_STATUS',
                target: 'SELF',
            },
        ],
        cost: 3,
        speed: 65,
        rarity: ItemRarity.Legendary,
        accuracy: 90,
    },
    {
        id: 'the_chokester',
        name: 'The Chokester',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'CHOKESTER',
                target: 'OPPONENT',
                turns: 3,
            },
        ],
        cost: 3,
        speed: 8,
        rarity: ItemRarity.Rare,
        accuracy: 80,
    },
    {
        id: 'maggiscared',
        name: 'Maggi Scared',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 3,
                accuracy: 25,
            },
        ],
        cost: 1,
        speed: 47,
        rarity: ItemRarity.Rare,
        accuracy: 100,
    },
    {
        id: 'sniff',
        name: 'Sniff',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'VIEW_HAND',
                target: 'SELF',
            },
        ],
        cost: 1,
        speed: 3,
        rarity: ItemRarity.Rare,
        accuracy: 100,
    },
    {
        id: 'are_you',
        name: 'Are You',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'RETARDED',
                target: 'OPPONENT',
                turns: 3,
                statusAccuracy: 33,
            },
        ],
        cost: 3,
        speed: 9,
        rarity: ItemRarity.Rare,
        accuracy: 90,
    },
    {
        id: 'kms2',
        name: 'Kms 2',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 1,
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
            },
        ],
        cost: 0,
        speed: 10,
        rarity: ItemRarity.Rare,
        accuracy: 95,
    },
    {
        id: 'yarrne',
        name: 'Yarrne',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'STEAL_CARD',
                target: 'OPPONENT',
            },
        ],
        cost: 2,
        speed: 19,
        rarity: ItemRarity.Rare,
        accuracy: 80,
    },
    {
        id: 'geggi_kill',
        name: 'Geggi Kill',
        series: 'mazariniCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 2,
            },
        ],
        cost: 2,
        speed: 42,
        rarity: ItemRarity.Rare,
        accuracy: 90,
    },
    {
        id: 'choke_shield',
        name: 'Choke Shield',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'CHOKE_SHIELD',
                target: 'SELF',
                turns: 6,
            },
        ],
        cost: 2,
        speed: 11,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        cannotMiss: true,
    },
    {
        id: 'turtle',
        name: 'Turtle',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'SLOW',
                target: 'OPPONENT',
                turns: 4,
            },
        ],
        cost: 2,
        speed: 4,
        rarity: ItemRarity.Rare,
        accuracy: 80,
    },
    {
        id: 'waiting',
        name: 'Waiting',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'WAITING',
                target: 'OPPONENT',
                turns: 2, //max turns
            },
        ],
        cost: 2,
        speed: 44,
        rarity: ItemRarity.Rare,
        accuracy: 95,
    },
    {
        id: 'catmygling',
        name: 'Catmygling',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'MYGLING',
                target: 'SELF',
                value: 2,
                turns: 3,
            },
        ],
        cost: 1,
        speed: 63,
        rarity: ItemRarity.Rare,
        accuracy: 99,
    },
    {
        id: 'eivindpride',
        name: 'Eivindpride',
        series: 'mazariniCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'EIVINDPRIDE',
                target: 'OPPONENT',
                statusAccuracy: 15,
                turns: 10,
                value: 2,
            },
        ],
        cost: 2,
        speed: 41,
        rarity: ItemRarity.Epic,
        accuracy: 100,
    },
]
