import { GameValues } from '../../../general/values'
import { ItemRarity } from '../../../interfaces/database/databaseInterface'
import { CCGCard, CCGCardType } from '../ccgInterface'

export const swCCG: CCGCard[] = [
    // ── COMMON ─────────────────────────────────────────────────────────────
    {
        id: 'sw_gonk_droid_n',
        name: 'Gonk Droid',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 3,
                condition: {
                    type: 'NUM_CARDS_PLAYED',
                    target: 'SELF',
                    comparator: '==',
                    value: 1,
                },
            },
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
                condition: {
                    type: 'NUM_CARDS_PLAYED',
                    target: 'SELF',
                    comparator: '==',
                    value: 1,
                    invert: true,
                },
            },
        ],
        cost: 0,
        speed: 40,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['DROID'],
    },
    {
        id: 'sw_battle_droid_n',
        name: 'Battle Droid',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_battle_droid_n',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_battle_droid_n',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['DROID'],
    },
    {
        id: 'sw_jarjar_n',
        name: 'Jar Jar',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        cost: 1,
        speed: 35,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['CREATURE', 'REPUBLIC'],
        effectImmunities: ['RETARDED'],
    },
    {
        id: 'sw_rebel_soldier_n',
        name: 'Rebel Soldier',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'REBEL',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'REBEL',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        cost: 1,
        speed: 45,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['REBEL'],
    },
    {
        id: 'sw_storm_trooper_n',
        name: 'Stormtrooper',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'SHOOT',
                target: 'OPPONENT',
                value: 1,
                amount: 5,
                accuracy: 40,
            },
        ],
        // Fire 5 shots. Each shot has 40% chance to hit
        cost: 1,
        speed: 55,
        rarity: ItemRarity.Common,
        accuracy: 100,
        identifier: ['EMPIRE'],
    },
    {
        id: 'sw_ewok_n',
        name: 'Ewok',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_ewok_n',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_ewok_n',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['CREATURE'],
    },
    {
        id: 'sw_clone_trooper_n',
        name: 'Clone Trooper',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'JEDI',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'SELF',
                    identifier: 'JEDI',
                    comparator: '>=',
                    value: 1,
                    invert: true,
                },
            },
        ],
        cost: 1,
        speed: 48,
        rarity: ItemRarity.Common,
        accuracy: 90,
        identifier: ['REPUBLIC'],
    },

    // ── EPIC ───────────────────────────────────────────────────────────────
    {
        id: 'sw_boba_fett_n',
        name: 'Boba Fett',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
                condition: {
                    type: 'HP_BELOW',
                    target: 'OPPONENT',
                    value: GameValues.ccg.gameSettings.startingHP / 2,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'HP_BELOW',
                    target: 'OPPONENT',
                    value: GameValues.ccg.gameSettings.startingHP / 2,
                    invert: true,
                },
            },
            {
                type: 'CLAIM_BOUNTY',
                target: 'OPPONENT',
                value: 3,
                accuracy: 100,
                condition: { type: 'HAS_STATUS', target: 'OPPONENT', status: 'BOUNTY' },
            },
        ],
        cost: 2,
        speed: 65,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['BOUNTY_HUNTER'],
        customDescription: 'Deal [red]4 damage[/red] if opponent is below 50% HP, otherwise deal [red]3 damage[/red]',
    },
    {
        id: 'sw_general_grevious_n',
        name: 'General Grievous',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE_PER_IDENTIFIER',
                target: 'OPPONENT',
                identifier: 'JEDI',
                countTarget: 'BOTH',
                base: 2,
                value: 1,
            },
        ],
        // Deal 2 damage + 1 for every JEDI card played by either player this round
        cost: 2,
        speed: 62,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['DROID'],
    },
    {
        id: 'sw_mace_windu_n',
        name: 'Mace Windu',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 5,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'BOUNTY_HUNTER',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'BOUNTY_HUNTER',
                    comparator: '>=',
                    value: 1,
                    invert: true,
                },
            },
        ],
        cost: 2,
        speed: 60,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['JEDI', 'REPUBLIC'],
    },
    {
        id: 'sw_darth_maul_n',
        name: 'Darth Maul',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        customDescription: 'Dual wields. Deal 2 damage, twice.',
        cost: 2,
        speed: 50,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['SITH'],
    },
    {
        id: 'sw_padme_amidala_n',
        name: 'Padme Amidala',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'NEUTRALIZE_ATTACK',
                target: 'OPPONENT',
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'JEDI',
            },
        ],
        // Neutralize the next incoming attack. Summon a random Jedi to hand
        cost: 2,
        speed: 80,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        cannotMiss: true,
        identifier: ['REPUBLIC'],
    },
    {
        id: 'sw_princess_leia_n',
        name: 'Princess Leia',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'REDUCE_COST',
                target: 'SELF',
                value: 1,
                turns: 2,
                identifier: 'REBEL',
            },
        ],
        // All rebel card costs are decreased by 1 for 2 turns
        cost: 1,
        speed: 40,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['REBEL'],
    },
    {
        id: 'sw_yoda_n',
        name: 'Yoda',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'ELUSIVE',
                target: 'SELF',
                turns: 2,
            },
        ],
        // Deal 3 damage. Apply ELUSIVE to self for 2 turns. (Elusive makes you harder to hit - effectively lowering opponent's accuracy 20%)
        cost: 2,
        speed: 12,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['JEDI', 'REPUBLIC'],
    },
    {
        id: 'sw_ahsoka_tano_n',
        name: 'Ahsoka Tano',
        series: 'swCCG',
        type: CCGCardType.Attack,
        customDescription: 'Deal [red]3 damage[/red]. [green]Heal 4[/green] instead if own HP below 5',
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'HP_BELOW',
                    target: 'SELF',
                    value: 5,
                    invert: true,
                },
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 4,
                condition: {
                    type: 'HP_BELOW',
                    target: 'SELF',
                    value: 5,
                },
            },
        ],
        cost: 2,
        speed: 58,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['JEDI'],
    },
    {
        id: 'sw_grand_moff_tarkin_n',
        name: 'Grand Moff Tarkin',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 6,
                condition: {
                    type: 'BUILD_DEATHSTAR',
                    target: 'SELF',
                },
            },
        ],
        cost: 2,
        speed: 42,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['EMPIRE'],
        customDescription: 'Use Death Star to deal [red]6 damage[/red]',
    },
    {
        id: 'sw_grand_admiral_thrawn_n',
        name: 'Grand Admiral Thrawn',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'MYGLING',
                target: 'OPPONENT',
                turns: 3,
            },
        ],
        cost: 1,
        speed: 55,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['EMPIRE'],
    },
    {
        id: 'sw_count_dooku_n',
        name: 'Count Dooku',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 5,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'JEDI',
                    comparator: '>=',
                    value: 1,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'JEDI',
                    comparator: '>=',
                    value: 1,
                    invert: true,
                },
            },
        ],
        cost: 2,
        speed: 30,
        rarity: ItemRarity.Epic,
        accuracy: 95,
        identifier: ['SITH'],
    },
    {
        id: 'sw_ig88_n',
        name: 'IG-88',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE_PER_CARD_PLAYED', //Add new effect type that counts number of cards played this round and multiplies by value
                target: 'OPPONENT',
                countTarget: 'BOTH',
                value: 1,
            },
            {
                type: 'CLAIM_BOUNTY',
                target: 'OPPONENT',
                value: 3,
                accuracy: 100,
                condition: { type: 'HAS_STATUS', target: 'OPPONENT', status: 'BOUNTY' },
            },
        ],
        // Deal 1 damage every card played this round (CARD_COUNT_BONUS: not yet implemented)
        cost: 2,
        speed: 60,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['BOUNTY_HUNTER', 'DROID'],
    },
    {
        id: 'sw_anakin_skywalker_n',
        name: 'Anakin Skywalker',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'TRANSFORM',
                target: 'SELF',
                accuracy: 33,
                transformCardId: 'sw_darth_vader_n',
            },
        ],
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Epic,
        accuracy: 100,
        identifier: ['JEDI', 'REPUBLIC'],
        customDescription: 'Deal [red]3 damage[/red]. [red]33% chance[/red] of turning to the dark side and becoming Darth Vader after this turn',
    },

    // ── RARE ───────────────────────────────────────────────────────────────
    {
        id: 'sw_r2d2_n',
        name: 'R2-D2',
        series: 'swCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'REMOVE_STATUS',
                target: 'SELF',
            },
        ],
        cost: 1,
        speed: 65,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['DROID'],
    },
    {
        id: 'sw_c3po_n',
        name: 'C-3PO',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                //TODO update eivindpride to use same
                type: 'PERSISTENT_APPEARANCE',
                target: 'OPPONENT',
                value: 1,
                turns: 5,
                accuracy: 40,
            },
        ],
        // 40% chance to appear and deal 1 damage for 5 turns
        cost: 1,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['DROID'],
    },
    {
        id: 'sw_chewbacca_n',
        name: 'Chewbacca',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'SPEED_BUFF',
                target: 'SELF',
                turns: 1,
                condition: {
                    type: 'PLAYED_EFFECT_TYPE',
                    target: 'OPPONENT',
                    effectType: 'DAMAGE',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        cost: 1,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['REBEL', 'CREATURE'],
    },
    {
        id: 'sw_han_solo_n',
        name: 'Han Solo',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
        ],
        cost: 2,
        speed: 999,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['REBEL'],
        customDescription: 'Deal [red]3 damage[/red]. Always shoots first.',
        effectImmunities: ['SLOW'],
    },
    {
        id: 'sw_admiral_ackbar_n',
        name: 'Admiral Ackbar',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'HAS_STATUS',
                    target: 'OPPONENT',
                    status: 'BUILD_DEATHSTAR',
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
                condition: {
                    type: 'HAS_STATUS',
                    target: 'OPPONENT',
                    status: 'BUILD_DEATHSTAR',
                    invert: true,
                },
            },
        ],
        cost: 1,
        speed: 25,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['REBEL', 'CREATURE'],
        customDescription: 'Deal [red]2 damage[/red]. [red]+1 damage[/red] if opponent has [pink]Death Star[/pink]',
    },
    {
        id: 'sw_grogu_n',
        name: 'Grogu',
        series: 'swCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 4,
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 1,
                condition: {
                    type: 'PLAYED_CARD_IDENTIFIER',
                    target: 'OPPONENT',
                    identifier: 'EMPIRE',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        cost: 2,
        speed: 15,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['CREATURE'],
    },
    {
        id: 'sw_lando_calrissian_n',
        name: 'Lando Calrissian',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                //TODO: maybe add possibility of setting odds for each effect instead of just 50/50?
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 5,
                gambleGroup: 'lando',
            }, //TODO: maybe rename gambleGroup to something more generic since it can be used for more than just lando cards
            {
                type: 'DAMAGE',
                target: 'SELF',
                value: 2,
                gambleGroup: 'lando',
            },
        ],
        // 50/50 between dealing 5 damage or taking 1 damage
        cost: 2,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['REBEL'],
        customDescription: '[yellow]50/50[/yellow]: Deal [red]5 damage[/red] or take [red]2 damage[/red]',
    },
    {
        id: 'sw_din_djarin_n',
        name: 'Din Djarin',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'ARMOR',
                target: 'SELF',
                value: 1,
                turns: 2,
            },
            {
                type: 'CLAIM_BOUNTY',
                target: 'OPPONENT',
                value: 3,
                accuracy: 100,
                condition: { type: 'HAS_STATUS', target: 'OPPONENT', status: 'BOUNTY' },
            },
        ],
        // Gain beskar armor. Reduce all direct damage by 1 for 2 turns
        cost: 1,
        speed: 25,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['BOUNTY_HUNTER'],
    },
    {
        id: 'sw_kit_fisto_n',
        name: 'Kit Fisto',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 1,
            },
        ],
        cost: 1,
        speed: 48,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['JEDI', 'REPUBLIC'],
    },
    {
        id: 'sw_plo_koon_n',
        name: 'Plo Koon',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_clone_trooper_n',
                    comparator: '>=',
                    value: 1,
                },
            },
        ],
        cost: 2,
        speed: 45,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['JEDI', 'REPUBLIC'],
    },
    {
        id: 'sw_cassian_andor_n',
        name: 'Cassian Andor',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'STEAL_ENERGY',
                target: 'OPPONENT',
                value: 2,
            },
        ],
        cost: 2,
        speed: 50,
        rarity: ItemRarity.Rare,
        accuracy: 90,
        identifier: ['REBEL'],
    },
    {
        id: 'sw_luthen_rael_n',
        name: 'Luthen Rael',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 4,
                turns: 3,
                delayedTrigger: true,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
                turns: 3,
                delayedTrigger: true,
            },
            {
                type: 'SLOW',
                target: 'SELF',
                turns: 3,
            },
        ],
        // Gain 4 energy and heal 3, in 3 turns. Apply SLOW for 3 turns
        cost: 2,
        speed: 20,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['REBEL'],
    },
    {
        id: 'sw_jabba_the_hutt_n',
        name: 'Jabba the Hutt',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'BOUNTY',
                target: 'OPPONENT',
                turns: 999,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                identifier: 'BOUNTY_HUNTER',
            },
        ],
        // Apply BOUNTY to opponent. Summon a random bounty hunter to hand
        cost: 1,
        speed: 35,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['CREATURE'],
    },
    {
        id: 'sw_k2so_n',
        name: 'K-2SO',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DISCARD_CARD',
                target: 'SELF',
                amount: 1,
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
        ],
        // Discards a random card from hand and deals 3 damage
        cost: 1,
        speed: 55,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['DROID'],
    },
    {
        id: 'sw_moff_gideon_n',
        name: 'Moff Gideon',
        series: 'swCCG',
        type: CCGCardType.Heal,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
            },
            {
                type: 'SUMMON_CARD',
                target: 'SELF',
                summonCardId: 'sw_dark_trooper_n',
            },
        ],
        // Heal 2. Summon a dark trooper to hand
        cost: 2,
        speed: 40,
        rarity: ItemRarity.Rare,
        accuracy: 90,
        identifier: ['EMPIRE'],
    },
    {
        id: 'sw_cad_bane_n',
        name: 'Cad Bane',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 2,
            },
            {
                type: 'STEAL_ENERGY',
                target: 'OPPONENT',
                value: 1,
            },
            {
                type: 'CLAIM_BOUNTY',
                target: 'OPPONENT',
                value: 3,
                accuracy: 100,
                condition: { type: 'HAS_STATUS', target: 'OPPONENT', status: 'BOUNTY' },
            },
        ],
        cost: 2,
        speed: 58,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['BOUNTY_HUNTER'],
    },
    {
        id: 'sw_bossk_n',
        name: 'Bossk',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'BLEED',
                target: 'OPPONENT',
                value: 1,
                turns: 3,
                includeCurrentTurn: true,
            },
            {
                type: 'CLAIM_BOUNTY',
                target: 'OPPONENT',
                value: 3,
                accuracy: 100,
                condition: { type: 'HAS_STATUS', target: 'OPPONENT', status: 'BOUNTY' },
            },
        ],
        cost: 1,
        speed: 55,
        rarity: ItemRarity.Rare,
        accuracy: 95,
        identifier: ['BOUNTY_HUNTER', 'CREATURE'],
    },
    {
        id: 'sw_director_krennic_n',
        name: 'Director Krennic',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'BUILD_DEATHSTAR',
                target: 'SELF',
                turns: 3,
            },
        ],
        // Build Death Star (3 turns). Acts as a status condition that other cards can check
        cost: 1,
        speed: 41,
        rarity: ItemRarity.Rare,
        accuracy: 100,
        identifier: ['EMPIRE'],
        customDescription: 'Build [yellow]Death Star[/yellow] for [pink]3 turns[/pink]',
    },
    {
        id: 'sw_dark_trooper_n',
        name: 'Dark Trooper',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_dark_trooper_n',
                    comparator: '>=',
                    value: 2,
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
                condition: {
                    type: 'PLAYED_CARD_ID',
                    target: 'SELF',
                    cardId: 'sw_dark_trooper_n',
                    comparator: '>=',
                    value: 2,
                    invert: true,
                },
            },
        ],
        // +1 dmg if played with another dark trooper
        cost: 2,
        speed: 62,
        rarity: ItemRarity.Rare,
        accuracy: 90,
        identifier: ['DROID', 'EMPIRE'],
    },

    // ── Legendary ───────────────────────────────────────────────────────────────
    {
        id: 'sw_luke_skywalker_n',
        name: 'Luke Skywalker',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 4,
                condition: {
                    type: 'HAS_STATUS',
                    target: 'OPPONENT',
                    status: 'BUILD_DEATHSTAR',
                },
            },
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 5,
                condition: {
                    type: 'HAS_STATUS',
                    target: 'OPPONENT',
                    status: 'BUILD_DEATHSTAR',
                    invert: true,
                },
            },
            {
                type: 'DESTROY_DEATHSTAR',
                target: 'OPPONENT',
                condition: {
                    type: 'HAS_STATUS',
                    target: 'OPPONENT',
                    status: 'BUILD_DEATHSTAR',
                },
            },
        ],
        cost: 2,
        speed: 45,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        identifier: ['JEDI', 'REBEL'],
        customDescription: "Deal [red]4 damage[/red]. [yellow]Destroy opponent's Death Star[/yellow] if built, otherwise [red]deal +1 damage[/red]",
    },
    {
        id: 'sw_qui_gon_jinn_n',
        name: 'Qui-Gon Jinn',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'GAIN_ENERGY',
                target: 'SELF',
                value: 2,
            },
            {
                type: 'HEAL',
                target: 'SELF',
                value: 2,
            },
        ],
        // Meditates. Gain 2 energy. Gain 2 hp
        cost: 1,
        speed: 5,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['JEDI', 'REPUBLIC'],
    },
    {
        id: 'sw_space_jesus_n',
        name: 'Space Jesus',
        series: 'swCCG',
        type: CCGCardType.Effect,
        effects: [
            {
                type: 'HEAL',
                target: 'SELF',
                value: 3,
            },
            {
                type: 'ARMOR',
                target: 'SELF',
                value: 1,
                turns: 1,
                includeCurrentTurn: true,
            },
        ],
        customDescription: 'Heal 3 and gain 1 armor for this turn',
        cost: 1,
        speed: 85,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['JEDI', 'REPUBLIC'],
    },

    {
        id: 'sw_darth_vader_n',
        name: 'Darth Vader',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'CHOKESTER',
                target: 'OPPONENT',
                turns: 1,
            },
        ],
        // Force choke opponent
        cost: 2,
        speed: 70,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        identifier: ['SITH', 'EMPIRE'],
        customDescription: '[red]Force choke opponent.[/red] Deal [red]3 damage[/red] and apply [pink]CHOKESTER[/pink] for 1 turn',
    },
    {
        id: 'sw_emperor_palpatine_n',
        name: 'Emperor Palpatine',
        series: 'swCCG',
        type: CCGCardType.Attack,
        effects: [
            {
                type: 'DAMAGE',
                target: 'OPPONENT',
                value: 3,
            },
            {
                type: 'SHOCK',
                target: 'OPPONENT',
                value: 2,
                turns: 2,
                includeCurrentTurn: true,
            },
        ],
        // Force lightning. Deal 3 damage. Target takes 2 shock damage for 2 turns
        cost: 3,
        speed: 75,
        rarity: ItemRarity.Legendary,
        accuracy: 100,
        cannotMiss: true,
        identifier: ['SITH', 'EMPIRE'],
        customDescription: '[red]Force lightning.[/red] Deal [red]3 damage[/red]. Target takes [red]2 shock damage[/red] for 2 turns',
    },
]
